# This file contains values from Cookiecutter

default_context:
  project_name: "pr-st-cli"
  project_description: "pr-st-cli is a CLI package that helps creates streamlit templates"
  organization: "gamcoh"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "gamcoh"
  email: "cohengamliel8@gmail.com"
  version: "0.0.1"
  line_length: "88"
  create_example_template: "cli"
